import Signup from "../../components/login/Signup";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { sendUserData, fetchUserdata } from "../../components/store/thunk";

export default function SignupPage() {
  const dispatch = useDispatch();
  const user = useSelector((state) => state.form);
  // console.log(user)
  // const cart=useSelector((state)=>state.cart.items)
  // console.log(cart);
  const stateChanged = useSelector((state) => state.form.stateChanged);

  useEffect(() => {
    dispatch(fetchUserdata());
  }, [dispatch]);

  useEffect(() => {
    if (stateChanged) dispatch(sendUserData(user));
  }, [dispatch, stateChanged, user]);

  return (
    <div className="bg-gradient-to-l from-gray-300 to-gray-100">
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />
    </div>
  );
}
